### ISSUE TITLE
Why doesn't LocalDateTime have plus/minusMilliseconds()?

### ISSUE THREAD

**Issue by cowwoc** [ThreeTen/threeten-extra#65] opened 2016-06-28 23:55 UTC
Out of curiosity, why does `LocalDateTime` have plus/minus hours, minutes, second and even nanoseconds, but not milliseconds? Is there a technical reason for this? Can it be added?

Yes, I am familiar with `plus(long amountToAdd, TemporalUnit unit)` but I'm wondering why all other units have dedicated methods and milliseconds does not.

**Comment by jodastephen** [comment] 2016-06-30 10:23
JSR-310 is based on nanoseconds, so all the relevant methods use that unit. While it would be possible to have `plusMillis()` it seemed like a suitable thing to omit given the existence of `plusNanos()`.

**Comment by cowwoc** [comment] 2016-06-30 18:14
How does `plusMillis()` differ from `plusSeconds()` in this regard? If you're going to have one, you should really have the other.

**Comment by jodastephen** [comment] 2016-06-30 18:37
Time is based on four fields - hours, minutes, seconds and nanoseconds. The API flows from that. Millis would be an overlapping concept. ie. it is not sensible to have NanosOfMilli as a field.

**Comment by cowwoc** [comment] 2016-06-30 20:00
I see where you're coming from, but it sounds like you're letting implementation details dictate API design/usability. Just because there is no underlying field for milliseconds doesn't mean that the API should not have a getter method.

Do users add/subtract milliseconds on a regular basis? If so, I would advocate adding this method.

I know for that for most time classes (especially the ones that measure time in terms of milliseconds from epoc) milliseconds manipulation is fairly common. In my case, I've got two `LocalDateTime` instances that represent a time range. For the exclusive endpoint, I need to calculate the inclusive endpoint that predates it (time - 1 millisecond) in order to convert it into an SQL statement.

**Comment by jodastephen** [comment] 2016-06-30 21:32
Ultimately, you need to file an issue at OpenJDK and lobby for its inclusion. Now JSR-310 is part of OpenJDK, my decision making powers are low.

**Comment by Clockwork-Muse** [comment] 2016-06-30 21:58
@cowwoc - (just a comment here...)
> In my case, I've got two  `LocalDateTime`  instances that represent a time range. For the exclusive endpoint, I need to calculate the inclusive endpoint that predates it (time - 1 millisecond) in order to convert it into an SQL statement.

Why inclusive?  Wouldn't it be better to do it as an exclusive bound?  All major databases can do better than milliseconds, most of them by default.  And why `LocalDateTime` - in most cases the time zone of the field will be known, even if it's not actually stored (ie, the convention to store date/time as UTC)

**Comment by cowwoc** [comment] 2016-06-30 23:40
> Why inclusive? Wouldn't it be better to do it as an exclusive bound?

MySQL's `BETWEEN` expects inclusive bounds.

> All major databases can do better than milliseconds, most of them by default.

Agreed, but the person who authored the DB schema decided to store dates as `BIGINT` in the DB (representing milliseconds since epoc in the UTC timezone). I know, I don't love it either ;)

> And why LocalDateTime - in most cases the time zone of the field will be known, even if it's not actually stored (ie, the convention to store date/time as UTC)

Correct, we assume that all database times are in UTC. As such, we wanted to avoid any sort of timezone conversions relative to the server's zone. Is there a problem with that?

**Comment by Clockwork-Muse** [comment] 2016-07-01 02:26
> MySQL's  `BETWEEN`  expects inclusive bounds.
That's the SQL standard, all RDBMSs do that.  And it's exactly why you shouldn't be using it, too.  Dates/times are a positive, contiguous-range type, and as such you [shouldn't use an inclusive upper bound, like used by `BETWEEN`](http://sqlblog.com/blogs/aaron_bertrand/archive/2011/10/19/what-do-between-and-the-devil-have-in-common.aspx) (yes, the blog is about SQL Server, but the underlying problem is actually due to representation.  There's also someting of a conceptual issue about how to regard time, too).  An exclusive upper-bound would be automatically safer in all cases.

> Agreed, but the person who authored the DB schema decided to store dates as  `BIGINT`  in the DB (representing milliseconds since epoc in the UTC timezone). I know, I don't love it either ;)

This really only makes sense if they're absolute (unix or otherwise) stamps, which leads into my next point...

> Correct, we assume that all database times are in UTC. As such, we wanted to avoid any sort of timezone conversions relative to the server's zone. Is there a problem with that?

The problem is that you're not avoiding zone conversions so much as pretending time zones don't matter.  At some point one of these is going to be used incorrectly elsewhere.  In most cases comparing properly zoned values is a trivial operation (compared to the cost of adding things like days or months).  
If you have an absolute UTC stamp, it's almost certainly a logged event, in which case the proper domain type is an `Instant` - and there's handy `ofEpochMillis`/`toEpochMillis` methods, too (there's also a `plusMillis` method, but that shouldn't be used to get an inclusive endpoint, so might not be handy in this case).

**Comment by cowwoc** [comment] 2016-07-01 08:38
> If you have an absolute UTC stamp, it's almost certainly a logged event, in which case the proper domain type is an `Instant`

Good point.

> there's also a plusMillis method, but that shouldn't be used to get an inclusive endpoint

Sorry, I don't get this part. Why shouldn't this be used to get an inclusive endpoint? :)

**Comment by Clockwork-Muse** [comment] 2016-07-01 09:22
Because, like for all positive, contiguous ranges, the proper thing to do is use an exclusive endpoint.  
Think about it like this; when is "today" no longer "today"?  When it's "tomorrow".  How many times can "today" be divided, in increasingly smaller steps - essentially, how many real numbers are there between 0 and 1?  An infinite number - there's always another instant (as in the concept, not the class) before tomorrow.  
It's a number representation problem - as you add precision, the effect is to add another '0' after the decimal point.  If you end up mixing types with different precisions, you can get weird effects if the end is inclusive and you don't take the difference into account (ie, subtracting just 1 of the more precise type); if it's exclusive you can just use whatever lower-precision type you're interested in, and not have to worry about what the precision of the underlying system is: if I want to get everything for the year 2016 I could use `someApi(fromYear:2015, beforeYear:2016)` - the underlying system might store it the relevant dates by year, month, day, millisecond, whatever, but the exclusive upper bound makes it trivial to work with.  I recommend going through the linked blog I posted once more.  
It's the same reason [why arrays start from 0 and are queried as `< array.count`](http://www.cs.utexas.edu/users/EWD/transcriptions/EWD08xx/EWD831.html).  And for the same reason that `rand`-type functions return values in the range `0 >= n > 1` (if the range is inclusive of the 1 and you're using it to generate integers, you have a verrrryyyyy small chance of getting one particular number...).

**Comment by cowwoc** [comment] 2016-07-01 22:55
My database contains a list of events (name, value and the time when they occurred). I am trying to query the database for all events that occurred between two endpoints.

Are you saying that I should replace `BETWEEN` with `time >= startTime AND time < endTime` where `endTime` is exclusive? Or are you saying something else?

**Comment by Clockwork-Muse** [comment] 2016-07-01 23:53
Yes, that's it exactly.  
Frankly, I'm of the opinion `BETWEEN` should be banned (except in maybe one optimization case, which usually isn't necessary if your db has geometry/gis capabilities or the optimizer is smart enough); the bounds being inclusive on both sides is almost never correct.

**Comment by cowwoc** [comment] 2016-07-01 23:53
Great advice. I'll try implementing this change on Monday ;) Thanks!

**Comment by jodastephen** [comment] 2016-07-07 09:27
Nothing to do in ThreeTen-Extra, so closing issue.

**Closed by jodastephen** 2016-07-07 09:27 UTC
Labels: Discussion

**Comment by cowwoc** [comment] 2016-07-07 16:20
As an aside, @Clockwork-Muse's proposal (replacing `BETWEEN`) worked for me. Thanks guys!
