### ISSUE TITLE
YearWeek.atDay

### ISSUE THREAD

**Issue by skleinei** [ThreeTen/threeten-extra#90] opened 2018-01-07 13:53 UTC
I think I found a bug, in YearWeek.atDay, when the days in the YearWeek overflow into the new year.

Test Case:

    @Test
    public void testAtDay() {
        YearWeek yearWeek = YearWeek.of(2015, 53);

        LocalDate date;

        date = yearWeek.atDay(DayOfWeek.MONDAY);
        assertEquals(LocalDate.of(2015, 12, 28), date);   // OK!

        date = yearWeek.atDay(DayOfWeek.SUNDAY);
        assertEquals(LocalDate.of(2016, 1, 2), date);   // ERROR: java.time.DateTimeException: Invalid value for DayOfYear (valid values 1 - 365/366): 368
    }

From looking at YearWeek.atDay it seems that the overflow into the new year is simply not handled (while the reverse is).

I believe the code should be changed to the following:

    public LocalDate atDay(DayOfWeek dayOfWeek) {
        Objects.requireNonNull(dayOfWeek, "dayOfWeek");
        int correction = LocalDate.of(year, 1, 4).getDayOfWeek().getValue() + 3;
        int dayOfYear = week * 7 + dayOfWeek.getValue() - correction;
        if (dayOfYear < 0) {
            int daysOfPreviousYear = Year.isLeap(year - 1) ? 366 : 365;
            return LocalDate.ofYearDay(year - 1, daysOfPreviousYear + dayOfYear);
        } else if ((Year.isLeap(year) && dayOfYear > 366) || (dayOfYear > 365)) {
            int daysOfPreviousYear = Year.isLeap(year - 1) ? 366 : 365;
            return LocalDate.ofYearDay(year + 1, dayOfYear - daysOfPreviousYear - 1);
        } else {
            return LocalDate.ofYearDay(year, dayOfYear);
        }
    }

**Comment by catull** [comment] 2018-01-07 18:15
First of all, January 2nd 2016 was a Saturday, the Sunday was on the 3rd of January 2016.

Only adding your test case with that change to `TestWeekYear` with no other changes, after a clean compile the test suite `TestYearWeek` completes without an error.

Are you sure you are using the latest version from master ?

By the way, the second assert in your test case is already covered with line 274 in
[TestYearWeek](https://github.com/ThreeTen/threeten-extra/blob/master/src/test/java/org/threeten/extra/TestYearWeek.java#L274)
```java
            {2015, 53, MONDAY,    2015, 12, 28},
```
To cover your first assert, add this line above or below:
```java
            {2015, 53, SUNDAY,    2016,  1,  3},
```
There is already a case for January 2nd being a Saturday, in line 273.

Unfortunately, your fix in `YearWeek#atDay` causes 4 tests to fail:

```log
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.threeten.extra.TestYearWeek
Configuring TestNG with: TestNG652Configurator
Tests run: 312, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 2.111 sec <<< FAILURE! - in org.threeten.extra.TestYearWeek
test_atDay(org.threeten.extra.TestYearWeek)  Time elapsed: 0.012 sec  <<< FAILURE!
java.time.DateTimeException: Invalid value for DayOfYear (valid values 1 - 365/366): 0
	at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
	at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
	at java.time.LocalDate.ofYearDay(LocalDate.java:287)
	at org.threeten.extra.YearWeek.atDay(YearWeek.java:688)
	at org.threeten.extra.TestYearWeek.test_atDay(TestYearWeek.java:446)

test_atDay(org.threeten.extra.TestYearWeek)  Time elapsed: 0 sec  <<< FAILURE!
java.time.DateTimeException: Invalid value for DayOfYear (valid values 1 - 365/366): 0
	at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
	at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
	at java.time.LocalDate.ofYearDay(LocalDate.java:287)
	at org.threeten.extra.YearWeek.atDay(YearWeek.java:686)
	at org.threeten.extra.TestYearWeek.test_atDay(TestYearWeek.java:446)

test_atDay(org.threeten.extra.TestYearWeek)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected [2016-01-02] but found [2016-01-01]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at org.threeten.extra.TestYearWeek.test_atDay(TestYearWeek.java:447)

test_atDay(org.threeten.extra.TestYearWeek)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected [2016-01-03] but found [2016-01-02]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at org.threeten.extra.TestYearWeek.test_atDay(TestYearWeek.java:447)


Results :

Failed tests:
org.threeten.extra.TestYearWeek.test_atDay(org.threeten.extra.TestYearWeek)
  Run 1: PASS
  Run 2: PASS
  Run 3: PASS
  Run 4: PASS
  Run 5: PASS
  Run 6: PASS
  Run 7: PASS
  Run 8: PASS
  Run 9: PASS
  Run 10: TestYearWeek.test_atDay:446 » DateTime Invalid value for DayOfYear (valid valu...
  Run 11: PASS
  Run 12: PASS
  Run 13: PASS
  Run 14: PASS
  Run 15: TestYearWeek.test_atDay:446 » DateTime Invalid value for DayOfYear (valid valu...
  Run 16: TestYearWeek.test_atDay:447 expected [2016-01-02] but found [2016-01-01]
  Run 17: TestYearWeek.test_atDay:447 expected [2016-01-03] but found [2016-01-02]
  Run 18: PASS
  Run 19: PASS
  Run 20: PASS
  Run 21: PASS
  Run 22: PASS
  Run 23: PASS
  Run 24: PASS
  Run 25: PASS
  Run 26: PASS
  Run 27: PASS


Tests run: 286, Failures: 1, Errors: 0, Skipped: 0
```

The code may look unintuitive, it does get checked extensively though.

**Comment by jodastephen** [comment] 2018-01-08 11:18
Duplicate of #87 AFAICT

**Closed** 2018-01-08 11:22 UTC
Labels: Discussion
